server.port=8083
appid=5d32cc23657aedb00385664734a5c874
url.weather=https://api.openweathermap.org/data/2.5/weather
logging.level.com.example.weather.controller=INFO
logging.level.com.example.weather.config=INFO
spring.application.name=weather
